- hosts: all
  environment:
    OP_SERVICE_ACCOUNT_TOKEN: "{{ lookup('env', 'OP_SERVICE_ACCOUNT_TOKEN') }}"
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      ansible.builtin.pacman:
        update_cache: true
        upgrade: yes
      changed_when: False
      when: ansible_distribution == "Archlinux"


    - name: Install community.general collection
      ansible.builtin.command: ansible-galaxy collection install community.general
      tags: bootstrap

# run roles
- hosts: all
  tags: base
  become: true
  ansible_python_interpreter: /opt/venv/bin/python
  roles:
    - base
