sudo_group: wheel
sillypoise_passwd: $6$VLa1CaTzt1XdFtnY$W1CwxzKhQXi840Ed/wkdLwGIghWDj9PymTfpS/7iNs4aXYawIBto1VXfVZs0FCUPh8j3xYM5jjKr9EZnTnJMg0

op_repo:
  name: "1password"
  description: "1Password Stable Channel"
  baseurl: "https://downloads.1password.com/linux/rpm/stable/$basearch"
  enabled: yes
  gpgcheck: yes
  repo_gpgcheck: yes
  gpgkey: "https://downloads.1password.com/linux/keys/1password.asc"

openssh:
  sftp_path: /usr/lib/ssh/sftp-server
  service: sshd
