sudo_group: wheel

op_repo:
  name: "1password"
  description: "1Password Stable Channel"
  baseurl: "https://downloads.1password.com/linux/rpm/stable/$basearch"
  enabled: yes
  gpgcheck: yes
  repo_gpgcheck: yes
  gpgkey: "https://downloads.1password.com/linux/keys/1password.asc"
