- name: system setup | nix | install nix in single-user mode
  shell: |
    sh <(curl -L https://nixos.org/nix/install) --no-daemon
  args:
    creates: /home/sillypoise/.nix-profile
  tags:
    - nix
    - system
    - setup

- name: software | nix | add home-manager channel
  shell: nix-channel --add https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz home-manager
  tags:
    - nix
    - home-manager
  when: ansible_distribution == "Fedora"

- name: software | nix | update nix channels
  shell: nix-channel --update
  tags:
    - nix
    - home-manager

- name: software | nix | install home-manager
  shell: nix-shell '<home-manager>' -A install
  tags:
    - nix
    - home-manager

- name: software | nix | create .config/nixpkgs directory for home manager config
  file:
    path: /home/sillypoise/.config/nixpkgs
    state: directory
    owner: sillypoise
    group: sillypoise
    # permissions so home-manager can write to it
    mode: '0755'
  tags:
    - nix
    - home-manager
  when: ansible_distribution == "Fedora"

- name: software | nix | copy home-manager configuration file
  copy:
    src: users/sillypoise/nix/home.nix
    dest: /home/sillypoise/.config/nixpkgs/home.nix
    owner: sillypoise
    group: sillypoise
    mode: '0644'
  tags:
    - nix
    - home-manager
    - packages

- name: software | nix | install packages via home-manager
  shell: sudo -i -u sillypoise home-manager switch -f /home/sillypoise/.config/nixpkgs/home.nix
  tags:
    - nix
    - home-manager
    - packages
