- name: software | one_password | import op GPG key
  tags: 
    - bootstrap
    - repositories
  ansible.builtin.command: gpg --keyserver keyserver.ubuntu.com --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  args:
    creates: "/root/.gnupg/pubring.kbx"

- name: software | one_password | download and unzip op binary
  tags:
    - bootstrap
    - packages
  ansible.builtin.unarchive:
    src: "https://cache.agilebits.com/dist/1P/op2/pkg/v2.30.0/op_linux_amd64_v2.30.0.zip"
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/op  # Prevents re-downloading

- name: software | one_password | create onepassword-cli group
  tags:
    - bootstrap
    - groups
  ansible.builtin.group:
    name: onepassword-cli
    state: present

- name: software | one_password | set permissions on op binary
  tags:
    - bootstrap
    - permissions
  ansible.builtin.file:
    path: /usr/local/bin/op
    group: onepassword-cli
    mode: '2755'
    state: file

- name: software | one_password | verify op cli installation
  tags:
    - bootstrap
    - verification
  ansible.builtin.command: op --version
  register: op_version
  changed_when: false

- name: software | one_password | display op cli version
  tags:
    - bootstrap
    - debug
  ansible.builtin.debug:
    msg: "Installed op version: {{ op_version.stdout }}"
