- name: software | one_password | import op gpg key
  tags: bootstrap,repositories
  ansible.builtin.rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc
  when: ansible_distribution == "Fedora"

- name: software | one_password | add op repository
  tags: bootstrap,repositories
  yum_repository:
    name: 1password
    description: "1Password Stable Channel"
    baseurl: "https://downloads.1password.com/linux/rpm/stable/$basearch"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "https://downloads.1password.com/linux/keys/1password.asc"

- name: software | one_password | install op cli
  tags: bootstrap,repositories,packages
  dnf:
    name: 1password-cli
    state: present

- name: software | one_password | verify op cli installation
  tags: bootstrap,repositories,packages
  command: op --version
  register: op_version
  changed_when: false

- name: software | one_password | display op cli version
  tags: bootstrap,repositories,packages,debug
  debug:
    msg: "Installed op version: {{ op_version.stdout }}"
