- name: software | one_password | import op GPG key
  tags:
    - bootstrap
    - repositories
  rpm_key:
    state: present
    key: "{{ op_repo.gpgkey }}"
  when: ansible_distribution == "Fedora"

- name: software | one_password | add op repository
  tags:
    - bootstrap
    - repositories
  yum_repository:
    name: "{{ op_repo.name }}"
    description: "{{ op_repo.description }}"
    baseurl: "{{ op_repo.baseurl }}"
    enabled: "{{ op_repo.enabled }}"
    gpgcheck: "{{ op_repo.gpgcheck }}"
    repo_gpgcheck: "{{ op_repo.repo_gpgcheck }}"
    gpgkey: "{{ op_repo.gpgkey }}"
  notify: restart dnf cache
  when: ansible_distribution == "Fedora"

- name: software | one_password | install op cli
  tags:
    - bootstrap
    - repositories
    - packages
  dnf:
    name: 1password-cli
    state: present
  when: ansible_distribution == "Fedora"

- name: software | one_password | verify op cli installation
  tags:
    - bootstrap
    - repositories
    - packages
  command: op --version
  register: op_version
  changed_when: false
  when: ansible_distribution == "Fedora"

- name: software | one_password | display op cli version
  tags:
    - bootstrap
    - repositories
    - packages
    - debug
  debug:
    msg: "Installed op version: {{ op_version.stdout }}"
  when: ansible_distribution == "Fedora"

