- name: software | python | ensure Python3 is installed and up-to-date
  ansible.builtin.pacman:
    name: python
    state: latest
  tags:
    - python
    - bootstrap
    - packages

- name: software | python | install development tools for pip
  ansible.builtin.pacman:
    name:
      - base-devel
      - openssl
      - bzip2
      - libffi
  state: present
  tags:
    - python
    - bootstrap
    - packages

- name: software | python | ensure pip is installed
  ansible.builtin.pacman:
    name: python-pip
    state: present
  tags:
    - bootstrap
    - python
    - packages

- name: software | python | upgrade pip3
  ansible.builtin.command:
    cmd: python3 -m pip install --upgrade pip
  tags:
    - python
    - bootstrap
    - packages

- name: software | python | install passlib
  ansible.builtin.pip:
    name: passlib
    state: present
    executable: pip3
  tags:
    - bootstrap
    - python
    - packages
