- name: software | python | ensure Python3 is installed and up-to-date
  ansible.builtin.pacman:
    name: python
    state: latest
  tags:
    - python
    - bootstrap
    - packages

# - name: software | python | install development tools for pip
#   ansible.builtin.pacman:
#     name:
#       - base-devel
#       - openssl
#       - bzip2
#       - libffi
#     state: present
#   tags:
#     - python
#     - bootstrap
#     - packages
#
# - name: software | python | ensure pip is installed
#   ansible.builtin.pacman:
#     name: python-pip
#     state: present
#   tags:
#     - bootstrap
#     - python
#     - packages
#
# - name: Ensure python-virtualenv is installed
#   ansible.builtin.pacman:
#     name: python-virtualenv
#     state: present
#   tags:
#     - python
#     - bootstrap
#     - packages
#
# - name: Create virtual environment for Python packages
#   ansible.builtin.command:
#     cmd: python3 -m venv /opt/venv
#   args:
#     creates: /opt/venv  # Prevents re-running if already exists
#   tags:
#     - python
#     - bootstrap
#
# - name: Upgrade pip within the virtual environment
#   ansible.builtin.command:
#     cmd: /opt/venv/bin/pip install --upgrade pip
#   tags:
#     - python
#     - bootstrap
#
# - name: Install passlib in the virtual environment
#   ansible.builtin.command:
#     cmd: /opt/venv/bin/pip install passlib
#   tags:
#     - python
#     - bootstrap
